-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activation_codes
(
    id integer NOT NULL,
    activation_code character varying(6) NOT NULL,
    creation_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    user_id integer NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    nationality_id text NOT NULL,
    birth_year text NOT NULL,
    is_activated boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.candidates_activations
(
    activation_code_id integer NOT NULL,
    candidate_id integer NOT NULL,
    PRIMARY KEY (activation_code_id)
);

CREATE TABLE public.employer_activation_by_system_users
(
    id integer NOT NULL,
    system_user_id integer NOT NULL,
    employer_id integer NOT NULL,
    activate_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(200) NOT NULL,
    web_adress character varying(100) NOT NULL,
    phone_number character varying(11) NOT NULL,
    is_activated boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers_activations
(
    activation_code_id integer NOT NULL,
    employer_id integer NOT NULL,
    PRIMARY KEY (activation_code_id)
);

CREATE TABLE public.job_positions
(
    position_id integer NOT NULL,
    position_name character varying(30) NOT NULL,
    PRIMARY KEY (position_id)
);

CREATE TABLE public.system_users
(
    user_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.candidates_activations
    ADD FOREIGN KEY (activation_code_id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.candidates_activations
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (user_id)
    NOT VALID;


ALTER TABLE public.employer_activation_by_system_users
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employer_activation_by_system_users
    ADD FOREIGN KEY (system_user_id)
    REFERENCES public.system_users (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_activations
    ADD FOREIGN KEY (activation_code_id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.employers_activations
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.system_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;